SELECT *
FROM THAMGIADT TG
JOIN giaovien g on g.MAGV = TG.MAGV
WHERE TG.MAGV = g.MAGV;
EXPLAIN SELECT GV.MAGV, GV.HOTEN
FROM GIAOVIEN GV
WHERE MAGV  NOT IN ( SELECT TG.MAGV
                   FROM THAMGIADT TG
                   WHERE TG.MAGV = GV.MAGV);
SELECT GV.MAGV, GV.HOTEN
FROM GIAOVIEN GV
WHERE NOT EXISTS ( SELECT *
                   FROM THAMGIADT TG
                   WHERE TG.MAGV = GV.MAGV);
SELECT GV.MAGV, GV.HOTEN
FROM GIAOVIEN GV
         JOIN thamgiadt t on t.MAGV = GV.MAGV
         JOIN bomon b on t.MAGV = b.TRUONGBM;
SELECT GV.MAGV, GV.HOTEN
FROM GIAOVIEN GV
WHERE  EXISTS (
    SELECT * FROM THAMGIADT TG
    WHERE TG.MAGV=GV.MAGV);
SELECT GV.MAGV, GV.HOTEN
FROM GIAOVIEN GV
WHERE EXISTS ( SELECT * FROM BOMON WHERE TRUONGBM=GV.MAGV);